### ISSUE TITLE
Support for Linux?

### ISSUE THREAD

**Issue by jgfoster** [SafeExamBrowser/seb-server#129]
I assume that the reason Linux is not supported is because as an open-source operating system one could hack the OS to avoid the limitations provided by SEB. Is that right or is there another factor (lack of demand, lack of resources to implement it, something else)?

In our case we have a computer lab with Ubuntu desktop systems that are managed by the campus IT services and students (and faculty!) do not have administrative/root access to the machines and I'm satisfied that they have an unmodified OS. Would there be any interest in SEB for Linux?

**Comment by lucaboesch** [comment]
I think your question would mostly relate to Safe Exam Browser, not Safe Exam Browser Server, @jgfoster.
Please post this question elsewhere, this is not the right place (https://github.com/SafeExamBrowser/seb-win-refactoring/issues maybe?, https://github.com/SafeExamBrowser/seb-win-refactoring/issues maybe?).
I recommend to close this issue.

**Comment by jgfoster** [comment]
You are right, this isn't the right place. Thanks!
