### ISSUE TITLE
Supporter and Exam Admin can`t change their password

### ISSUE THREAD

**Issue by christinelent** [SafeExamBrowser/seb-server#140]
**Describe the bug**
Exam Supporter and Exam Administrator can`t change their password. (They don`t see the button on the right side)

Plus: As SEB Server Administrator I can`t change the password of another user, I always get the error message that the old password is wrong.

**To Reproduce**
1. Go to Seb Server, Login
2. Click on User Accounts.
3. No option to change the password on the right side

**Expected behavior**
User should be able to change their password

**Setup (please complete the following information):**
 - SEB Server Version v.2.0.2
 - Browser Chrome & Opera

**Comment by anhefti** [comment]
Hi, Thanks you for the input. We already discovered this bug and fixed it for the next version of SEB Server 2.1 that is comming out Q1 25.
We also discuss if there will be an additional patch release 2.0.3 coming out soon that would fix this issue before the next release.
Meanwhile you can change the password of other users either as SEB Server Administrator or with Institutional Administrator

> Plus: As SEB Server Administrator I can`t change the password of another user, I always get the error message that the old password is wrong.

To change a password for another user you need to enter first your own password and then the new password for the other usser. There is no old password you need to know or enter.

**Comment by christinelent** [comment]
> I just recognized that the validation message is sligtly wrong in the case you enter a wrong password when changing the password on an other user:
> 
> 
> The validation messages says "The old password is wrong" but this should correctly say: "Your password is wrong" instead. We will fix that text too.

The password was correct, as I entered it from an editor/plain text myself but still got the error message. So rn I have no chance to change a password for someone else.

**Comment by anhefti** [comment]
Password is encrypted and matched with well defined security API, SEB Server itself has not direct access to this.

So if you change Password for another user you must fist enter your own password. Our own password must be the same as you logged into SEB Server yourself. So it should match if you was able ot login to SEB Server.

If this is still not the case, you can try to view the SEB Server logs while doing the action and check if there is something stated.
