### ISSUE TITLE
Not clear what the purpose of this system is

### ISSUE THREAD

**Issue by sanmai-NL** [SafeExamBrowser/seb-server#19]
As an instructor in higher education, lecturing on both the development and operation of software systems, and currently coordinating digital assessments for our academy, _still_, I do not understand from the README alone what the purpose of this SEB Server system is. What place may it have inside an enterprise architecture? What is its role within the software architecture of the SEB solution in general? When should this be used over other solutions? Are there other solutions? What kind of requirements are there in relation to the described LMS'es? Do we need to use those too, or will this function independently?

This concerns me a lot. The work may go to waste if documentation/’marketing’/outreach fails. I think it's justified to complain about this at this stage already, because the mission of this project should be clear before work starts.

Can you solve this, and how can I help you in solving this?

**Comment by danschlet** [comment]
The reason for not promoting SEB Server generally is, that its development was separately financed for a Swiss higher education project ([Swiss MOOC Service SMS](https://www.swissmooc.ch)) and therefore SEB Server initially was only compatible to Open edX. As all our SEB-related developments, we make the product available as open source for the whole world, but for obvious reasons we have to focus first on the project it has been financed for.

Now that the SMS project is ending, we are working on making SEB Server available for other Safe Exam Browser use cases and for other LMS. The Moodle integration is not yet finalized, so for once we didn't try to promote something unfinished (having to answer questions about release dates all the time for which we don't have an answer yet). We are not a commercial entity and have limited resources, you have to consider that. Don't worry, at the right time, which will be soon, we will promote SEB Server properly (again compatible with our non-commercial structure!).

For now you can watch the video we made about  [Remote Exams With Safe Exam Browser ](https://www.youtube.com/watch?v=6GEn_NWnZe8), in the end SEB Server is shown shortly. Remote exams are an important use case for the need of a server component, which helps monitoring SEB clients. The first official release of SEB Server didn't offer a lot of advantages over for example the new improved SEB integration in Moodle 3.9. Upcoming versions will support Moodle and offer unique functionality (such as remote proctoring features, which are in prototyping state right now), so those will be worth promoting. Don't forget that people want to see demo videos and try such a new product themselves, and it requires a lot of effort and work to get such resources ready.

If you want to get more information than is available publicly about SEB Server, there is a way: Your organization can become member in the [SEB Consortium](https://safeexambrowser.org/consortium/members.html), which also contributes to the project so we can hire more staff to be able to improve documentation etc.

**Comment by danschlet** [comment]
Just a comment: There already is A LOT of technical documentation online for SEB Server. If you spend some time reading it, you will understand what it is and what it does. This is no marketing documentation, yes, but as I explained, we're not yet in that state of the "product lifecycle" or whatever you would call that as you seem to be the specialist given that you're lecturing on both the development and operation of software systems.

**Comment by sanmai-NL** [comment]
What is propose is this: make, in the README, immediately clear what the purpose is. There a lot of text already, but not the information I sought or would expect in a README.

I think this issue can be resolved straight away and would not need formal involvement in the project. It's not a marketing effort but it is a simple popularization effort beyond the technical docs. Thanks for the invitation though.

I already seen the video, it looks encouraging, still not so clear how everything ties in.

**Comment by danschlet** [comment]
We're actually just working on a news post about SEB Server and will surely improve this README as well, before a public announcement of SEB Server. But I think even with an improved "About" text or introduction, 
studying some documentation will be necessary to fully understand the whole e-assessment system based on SEB, SEB Server and an LMS/exam system. Or an introductory video, which takes a lot of time or resources to produce properly. So that's the trade off when using an open source freeware solution, which doesn't have resources to pay for professional documentation and marketing staff: In the beginning it's maybe only usable for tech guys who are used to figure out themselves how to use such software. Anyways, that's the people we're addressing right now. The less technologically capable people require a lot of support, which we cannot and are not willing to give right now!

About
The Safe Exam Browser Server web application simplifies and centralizes the configuration of SEB clients for exams. It interacts with a learning management or exam system for setting up and conducting e-assessments with Safe Exam Browser. It also improves security by allowing to monitor connected SEB clients in real time during e-assessments.

**Comment by sanmai-NL** [comment]
I understand your position and the funding situation. 

I deliberately described my expertise, and I saw the video, still it wasn't clear. I'm not saying it should be crystal clear yet for every conceivable stakeholder, but it should be for the target audience of experts. Apparently, it isn't always. So that's an observation I share.

**Comment by danschlet** [comment]
Feedback is always welcome. We grew a bit cautious over time when and how to communicate new projects and features, as some people react with very demanding support issues/questions, basically expecting us to give them a personal course on how to use our software for their use case or exam system, for free and immediately. Those guys obviously don't understand how open source development works and that there's no free lunch even in the case of the non-commercial nature of our operations. We don't keep our repositories private, but those things which are not mentioned in the documentation/manuals on safeexambrowser.org should basically be considered work in progress and therefore neither fully comprehensible for non-insiders nor final (I actually should have mentioned this first).

**Comment by sanmai-NL** [comment]
Yes, and I offer to contribute apart from the financial support route.

It's a bit discouraging to contribute when you find something of which the purpose isn't even clear to you, regardless of the _technical_ docs.
