### ISSUE TITLE
How to show /exams page to anonymous users just as https://demo.safeexambrowser.org/exams/ ?

### ISSUE THREAD

**Issue by fishfree** [SafeExamBrowser/seb-server#29]
I'd like to expose a exams portal page to students as the way https://demo.safeexambrowser.org/exams/ does. But SEB server seems lacking this feature.

**Comment by danschlet** [comment]
That exam portal page is just a simple HTML page where I put these links manually. When a SEB client is connected to SEB Server, the list of current exams is automatically displayed and students can select those exams. If you want a sebs:// link to a config file which connects students to a SEB Server instance, you can create such a simple HTML page or use some LMS or content management system which can serve resources like .seb files and where you can place sebs:// links or you just email students the sebs:// link.
