### ISSUE TITLE
After Entering into Moodle Quiz inside SEB .... It isnt getting triggered on SEB server exam monitoring section.

### ISSUE THREAD

**Issue by TirushV** [SafeExamBrowser/seb-server#32]
Hello!
Im Tirush (Cloud Engineer) we have been working on a project since 2 weeks (Remote Proctoring Exams With Safe Exam Browser)
we have deployed three individual servers on AWS - SEB server, Jitsi server (JWT authentication) , Moodle server. We have integrated Moodle LMS setup on SEB server and Quiz was triggered in SEB exam Lookup we have imported the exam and added required exam configurations and enabled Proctoring settings and Integrated it with Jitsi server and after that we have downloaded the config file and tried testing it ..... but the issue was my windows laptop SEB client isnt getting connected to SEB server........ Here after so much of research i have tried configuration of quiz on IPAD enabled all required configurations for Remote Proctoring exam with SEB. Im able to enter  SEB and quiz but that isnt getting triggered in Exam monitoring section like people who tried to attempt the exam it isnt showing on Exam monitoring section that means this isnt connecting to SEB server .... Kindly Help us with that .... we are expected help from you as soon as possible.
Thank You.

**Comment by anhefti** [comment]
Hello Tirush

Please check first if you have setup the SEB Server with the correct external URL settings that are needed for the Connection Configuration. To do so, please refer to the installation guide here: https://seb-server-setup.readthedocs.io/en/latest/overview.html and make sure the following settings are set correctly:

//This settings define the external URL where the SEB Server service can be connected from external Internet or VPN
sebserver.webservice.http.external.scheme=[http|https]
sebserver.webservice.http.external.servername=[example.sebserver.com]
sebserver.webservice.http.external.port=[has only to be set if differs from the default port of the scheme above]

So if your SEB Server installation is accessable from outside within the example URL https://example.sebserver.com
Then the settings should be like following:

sebserver.webservice.http.external.scheme=https
sebserver.webservice.http.external.servername=example.sebserver.com
sebserver.webservice.http.external.port=

You can check if the external URL settings are correct within the SEB Server startup logs:

![image](https://user-images.githubusercontent.com/39078777/128033690-8b97fc3e-694f-4f5b-9333-4ccf1904494b.png)


After this is correctly setup. You need to have a Connection Configuration. This is the only configuration that SEB needs to connect to the SEB Server. The Exam Configuration will then automatically be downloaded by the SEB client when connecting to the SEB Server. To do please refer to: https://seb-server.readthedocs.io/en/latest/connection_config.html
Create a Connection Configuration that has "Starting an Exam" as purpose and is active. Then click on "Export Connection Configuration" to export this configuration and after all start the SEB with this configuration. The SEB should connect to the SEB Server and give a selection with all running exams. Make also sure the exam you want to test is running. It should appear under "Running Exams" section. Make also sure you have a SEB client for iOS that already has SEB Server integration as well as live proctoring integration. This must be the newest available version.

If you have deeper SEB integration within your Moodle and problems setting up the SEB integration on Moodle side for working with SEB Server, please provide us with the needed information of your Moodle quiz setup too so we can have a look.

After all, please be aware that live proctoring is still an experimental feature and may not work as expected. And also the Moodle integration within SEB Server is yet just partly finished (no course restriction feature).

**Comment by TirushV** [comment]
Firstly Thank you so much for the instant reply with all the information sir... actually me and my 2 friends are working with this project to make this available for a small college in our village(Karakambadi). we thought we almost got this ........but stopped with this error. Just trying to help our small college for remote proctoring exam with SEB. Im trying to gain knowledge in this to implement in our own college for free under NGO act.

**Comment by TirushV** [comment]
URL - https://newtest.bbbitlf.net/moodle
Moodle credentials - user = admin, password = Password4!

**Comment by TirushV** [comment]
Sir actually I was trying this but couldn't fix the issue that SEB client isn't getting connected to the SEB server. Please if possible can you elaborate this or with any other documentation which helps to fix this issue. Here, only connection configuration isn't working rest everything was good and working well.

**Comment by danschlet** [comment]
Maybe it has to do with some changes when connecting introduced in latest versions of SEB Server. Connecting SEB 3.0 for iOS with the SEB Server version it was tested with (see this config sebs://demo.safeexambrowser.org/exams/SEBServerSettingsSMSTest.seb and Moodle works perfectly. But maybe it doesn't work with the SEB Server version you installed.

I will update the SEB Server integration in SEB 3.1 for iOS.

**Comment by TirushV** [comment]
Thank you so much for the instant reply with valuable information sir.

**Comment by anhefti** [comment]
TirushV, please can you send me (attach here) a downloaded Connection Configuration from your SEB Server, that has no password set. Then I can check whether there is a Problem with your SEB Server setup or something different. Also helpful would be the SEB log files.

**Comment by TirushV** [comment]
Sure sir 
[quiz1_2021-8-4.zip](https://github.com/SafeExamBrowser/seb-server/files/6930172/quiz1_2021-8-4.zip)
actually it will get stuck at initializing SEB server...

**Comment by TirushV** [comment]
[quiz1_2021-8-4 (1).zip](https://github.com/SafeExamBrowser/seb-server/files/6930221/quiz1_2021-8-4.1.zip)
without any password

**Comment by anhefti** [comment]
Thanks Tirush... It seems that you have a SEB Server demo Setup and and the changes I mention above are still not applied. In the Connection Configuration you sent me I'm able to see the connection URL of the SEB Server that is still set to the default at ETH

```
<key>sebServerURL</key>
    <string>http://ralph.ethz.ch:8080</string>
```

Please apply the settings as I mention in my first reply to your SEB Server setup:

sebserver.webservice.http.external.scheme=[http|https]
sebserver.webservice.http.external.servername=[example.sebserver.com]
sebserver.webservice.http.external.port=[has only to be set if differs from the default port of the scheme above]

I also recommend to not install the Demo version but either the basic test or basic prod version from the Docker Setup repository. Because this comes with fresh and clean data setup.

Please also have always a look at the SEB Server log after startup. You can find the most important settings there to quickly check the correctness of the setup.

![image](https://user-images.githubusercontent.com/39078777/128158880-040c0939-91e2-4974-954c-60a7329f37f6.png)

**Comment by TirushV** [comment]
Thank you so much for the information sir im looking into it

**Comment by TirushV** [comment]
I tried with PROD version and configured required changed in files but was not able to reach the server with any port.

**Comment by anhefti** [comment]
If you are not able to reach the Server at all via die Internet, please contact your system administrator. 
If just SEB is not connecting to the SEB Server, please send me again a Connection Configuration so we can have a look at it

**Comment by TirushV** [comment]
Sir can I have your Skype ID or Email id to connect with you please?

**Comment by anhefti** [comment]
Dear Tirush, this is an open source project and private support is not included. If you need valuable support please consider joining the [SEB Alliance](https://safeexambrowser.org/alliance/members.html)

If you can provide us with enough information (in this forum) about your setup and your problem we might be able to give some help.
