### ISSUE TITLE
Video not working in SEB 3.2

### ISSUE THREAD

**Issue by azmatksa** [SafeExamBrowser/seb-server#33]
**Describe the bug**
I'm using Moodle version 3.11 and I tried with two separate domain by uploading Mp4 video but SEB 3.2 showing either video not supporting or sometime its continue loading.

**To Reproduce**
1. Create  a quiz 
2. Upload any mp4 video
3. Access SEB from learner account

**Expected behavior**
Video should be display as displaying in normal browser

**Setup (please complete the following information):**
 - SEB Server Version 3.2

**Comment by anhefti** [comment]
Hi, this is the SEB Server board. SEB Server is another component that can be setup to carry out e-assessments with Safe Exam Browser (SEB) 
As you are working with SEB client for windows, you should post the issue in the SEB windows board that you will find here. https://github.com/SafeExamBrowser/seb-win-refactoring
