### ISSUE TITLE
Connection configuration with Moodle Config Key for Quiz

### ISSUE THREAD

**Issue by nimalr** [SafeExamBrowser/seb-server#35]
Hi, 

Using SEB Server v1.2-stable prod/bundled/dockerhub 

I can successfully connect to the SEB Server with the exported Connection configuration, but when I start the exam, SEB Client says "Loading New SEB Settings Not Allowed" and I cannot attempt the quiz.  The LMS (Moodle 3.10) has a Config Key set for the quiz.
<img width="797" alt="Screenshot 2021-08-19 at 22 08 53" src="https://user-images.githubusercontent.com/2149734/130108664-de0a9763-f769-46e2-a7fa-a3c18ce28eca.png">

 What is wrong in my Connection configuration?

<img width="763" alt="Screenshot 2021-08-19 at 21 03 31" src="https://user-images.githubusercontent.com/2149734/130108334-86bc2f12-0893-4fca-bb69-ac29173e6a99.png">

Nimal R.

**Comment by nimalr** [comment]
The problem may be that I am unable to import the exported config key from SEB Server into Moodle.

**Comment by anhefti** [comment]
Dear nimalr

The Config Key is been generated from the Exam Configuration that is bound to an Exam not from the Connection Configuration. The Connection Configuration is used only for SEB to be able to connect to securely the SEB Server. After that SEB Server sends a List of running Exams to the SEB for selection (except the Connection Configuration was exported via Exam and has already preselected the Exam). Once the exam is selected, SEB requests the Exam Configuration from SEB Server that is assosiated within the Exam and reconfigure itself. This configuration is then used to connect to Moodle and also the Config Key of this Exam Configuration is used on Moodle side if Moodle uses restricted SEB access.

The SEB Server Moodle integration is not yet complete and only the course-access features are done in SEB Server version 1.2. The automated Config Key restriction is not yet implemented and has to be done manually by copy the Config Key generated by the SEB Server for the specified exam and paste it in the Moodle in the relevant Moodle exam administration form.

To get the generated Config Key form SEB Server go to the specific exam on SEB Server, select the exam configuration within the exam and use the "Export Config Key" action. Now you can copy the Config Key from the popup.

![image](https://user-images.githubusercontent.com/39078777/130736183-0c55dd83-18cb-414d-851f-ca40a6dd7ec8.png)
