### ISSUE TITLE
Proctoring with jitsi-meet

### ISSUE THREAD

**Issue by cIeNso** [SafeExamBrowser/seb-server#44]
Hi there,

I set up a SEB server instance with Moodle and an additional jitsi server for proctoring. I was wondering if you could elaborate a bit on how exactly the video proctoring feature is supposed to work. Does the exam supporter have to start the proctoring room for a certain exam first before all the examinees are collected in the video conference room? Or do the examinees enter the video conference automatically on starting the SEB? If so, are examinees able to view the conference room and the other participants as well or is the proctor the only one to have access to their video stream?

I noticed an icon for video proctoring on the bottom right of the SEB but couldn't manage to get the examinee to enter a proctoring session yet. The exam supporter is able to enter the jitsi conference though as the only participant. I tried several configurations and I also get the notification on SEB start up that the current session is being monitored via video conference. On certain occasions I also managed to get the green proctoring icon which I believed to be an indicator for a working proctoring session. But I still can't see the examinee in the proctoring room.  Also in the seb logs I couldn't really find anything pertaining to the problem. Do you have any suggestions how I could approach this issue?

Thanks in advance.

**Comment by anhefti** [comment]
As we've discussed your questions within mail, is there any other open question to discuss here? Otherwise I will link to general documentation and to live proctoring documentation within this issue and close it.

**Comment by cIeNso** [comment]
No further questions. Thanks again for your help.
