### ISSUE TITLE
Support for LTI 1.3 Proctoring Services

### ISSUE THREAD

**Issue by jeroenhabets** [SafeExamBrowser/seb-server#51]
Merry Christmas!

Does the SEB Server team have any plans to support the IMS Global LTI standard for Proctoring Services? If so, any idea when?

http://www.imsglobal.org/proctoring-services

Currently only two LMS's edX and Moodle are supported. Supporting this standard would enable any LMS or Exam tool with LTI 1.3 Proctoring Services support to integrate with SEB Server through configuration (not development).

Specification: http://www.imsglobal.org/spec/proctoring/v1p0

Kind regards,
Jeroen Habets

**Comment by anhefti** [comment]
Hi Jeroen hand happy new Year!

Unfortunately no, the LTI standard for Proctoring Services was not on our radar yet. Currently SEB Server and SEB supports remote proctoring with Jitsi Meet and Zoom, independently from type of LMS that is been used. The LMS integration on SEB Server (development) is done to query course data to setup exams and apply configuration for automated assessments using SEB.  

But this might be a good addition to the existing support on SEB Server side for SEB proctoring. 
I will propose to discuss this within the team to get a closer look at the specification and to get a better understanding of the LTI proctoring service and its functionality first.

Thank you for the info.
Kind regards,
Andreas Hefti

**Comment by jeroenhabets** [comment]
Hi Andreas,

Thanks! And thanks for getting back to me!
I'll be looking forward to hearing the outcome of your discussions with the team.

For better understanding perhaps you find the following links are useful:

- IMS/Examity video ("Learning Impact On-Demand: Proctoring", Jan 2021): https://www.youtube.com/watch?v=jEmZPtBkWIU
- TOA Implementation (PHP): https://github.com/oat-sa/extension-lti-proctoring

Kind regards,
Jeroen Habets

**Comment by anhefti** [comment]
No planed support
