### ISSUE TITLE
Moodle Test - SEB Configurator URL: Whitelist - Textlength or max Entries 10

### ISSUE THREAD

**Issue by JuProTUDa** [SafeExamBrowser/seb-server#54]
Hi SEB-Team,

the moodle configurator can handle only 10 entries of URL.
10 entries are  to few in some settings. 

Here is my example for a DemoExam with BYODs. This config is intended for starting via moodle.
https://sso.tu-darmstadt.de*
https://moodle-exam.tu-darmstadt.de/mod/quiz*
https://safeexambrowser.org*
https://oeis.org/wiki/List_of_LaTeX_mathematical_symbols*
https://latex-tutorial.com/tutorials/amsmath*
https://www.deepl.com*
https://webdemo.myscript.com/views/math/index.html
https://www.desmos.com/scientific*
https://hessenbox.tu-darmstadt.de/getlink/fi8dHc7SZp63Wcd8rGSAVAtq/DemotextDateiZumDownload.zip
https://hessenbox.tu-darmstadt.de/dl/fi8dHc7SZp63Wcd8rGSAVAtq/DemotextDateiZumDownload.zip

For an analog demoexam for CIPs are more URLs needed. The next URL Whitelist is intended via direct config start:
https://moodle-exam.tu-darmstadt.de/theme*
https://moodle-exam.tu-darmstadt.de/lib*
https://moodle-exam.tu-darmstadt.de/login*
https://cdn.jsdelivr.net/npm*
+
https://sso.tu-darmstadt.de*
https://moodle-exam.tu-darmstadt.de/mod/quiz*
https://safeexambrowser.org*
https://oeis.org/wiki/List_of_LaTeX_mathematical_symbols*
https://latex-tutorial.com/tutorials/amsmath*
https://www.deepl.com*
https://webdemo.myscript.com/views/math/index.html
https://www.desmos.com/scientific*
https://hessenbox.tu-darmstadt.de/getlink/fi8dHc7SZp63Wcd8rGSAVAtq/DemotextDateiZumDownload.zip
https://hessenbox.tu-darmstadt.de/dl/fi8dHc7SZp63Wcd8rGSAVAtq/DemotextDateiZumDownload.zip 

Ideas:
Please change the GUI to longer textfields or make variable list of entries where each entry is standing alone.

Moodle 3.11 latest stable Version
Version 101.0.4951.54 (Offizieller Build) (64-Bit)

**Comment by danschlet** [comment]
I'm sorry, but we are not developing or supporting the SEB integration in Moodle. You have to create support issues on moodle.org.

SEB and SEB configuration files don't have a limit for the number of URL filter rules. You can create your own config files using the SEB Configuration Tool or SEB for Mac Preferences window (also see the interactive [Teach SEB allowed/blocked URLs](https://safeexambrowser.org/macosx/mac_usermanual_en.html#NetworkPaneFilterSection) feature in the SEB for macOS version) and use it for Moodle quizzes with the option "Yes - upload my own config".
