### ISSUE TITLE
Moodle Quiz-SEB Configurator - online Help for URL Whitelist and Regex - More Details please

### ISSUE THREAD

**Issue by JuProTUDa** [SafeExamBrowser/seb-server#55]
Hi SEB-Team,

It is not a bug or feature. It is manual thing.
The URL Whitelist has no hint what is the delimiter between the expression is like.
Please insert a sentence like: Use a new line for the next expression.

The help of the regex is at least in german useless. There is no hint which notation is used.

Where to find:
Go to the Safe Exam Browser properties for moodle quiz.
Look at the ? Symbols.
Here is the german version:
Expressions: 
![image](https://user-images.githubusercontent.com/105719467/168816245-9906438d-e891-4f36-b688-77ce3e4040df.png)
![image](https://user-images.githubusercontent.com/105719467/168816404-eeb22289-2eb8-4077-b40c-38fe56cca9f4.png)

Regex:
![image](https://user-images.githubusercontent.com/105719467/168816458-98089791-eb27-4d48-b5bf-7f76f2697ed6.png)
![image](https://user-images.githubusercontent.com/105719467/168816541-1325c2e4-e175-4f2c-a81b-0c99a73b4ea8.png)

Expected behavior
Expressions Help
Insert: The delimiter between  expressions is newline.
Regex Help
Please explain how to regex with SEB

Moodle 3.11 latest stable version

**Comment by danschlet** [comment]
I'm sorry, but we are not developing or supporting the SEB integration in Moodle. You have to create support issues on moodle.org. 

Regarding using regular expressions for URL filters, see the SEB manuals ([Mac](https://safeexambrowser.org/macosx/mac_usermanual_en.html#NetworkPaneFilterSection)/[Windows](https://safeexambrowser.org/windows/win_usermanual_en.html#NetworkPaneFilterSection)). Regular expressions may help for complex URL filters, but they are complex to understand (see any literature about regular expressions).
