### ISSUE TITLE
SEB Client Monitoring

### ISSUE THREAD

**Issue by ano010** [SafeExamBrowser/seb-server#58]
**Describe the bug**
SEB server shows some client is missing even after the clients are disconnected when multiple SEB clients have been connected to the SEB server. I tried to force quit all the clients in the SEB server using the option "Quit All SEB Clients" but still the issue exists. It shows some clients are missing. It prevents some other functions in SEB sever. For example, the associated exam can not be deleted since the client connection persists.

**To Reproduce**
1. Setup an LMS with type Moodle, Import the exam, define and attach a configuration to the exam
2. Download the exam connection configuration and connect to the SEB server using the configuration from two or more machines.
3. See in the exam monitoring whether the client status is "Active"
4. Disconnect all the clients and notice if it shows the status "Missing" for any client connection.
5. Notice the missing client is assigned to the proctoring room if the proctoring is enabled.

**Expected behavior**
The client should be disconnected from the SEB server, its status should be "Closed", there should not be any proctoring room. The server should disconnect all the client after the force quit using "Quit All SEB Clients". And the exam can be deleted if there is no any client connection.

**Screenshots**
<img width="926" alt="Screenshot 2022-06-13 131422" src="https://user-images.githubusercontent.com/33832254/173305215-1db3123a-2d5a-42f1-a1b6-fb7ff4d3de4c.png">

**Setup:**
 - SEB Server Version [v1.3-stable]
 - The server is running on Azure Kubernetes Service
 - Browser [chrome]

**Comment by anhefti** [comment]
Hi

This seems like the expired SEB connection token issue we lately discovered by ourselves with the 1.3 Version of SEB Server. This will going to be permanently fixed within the next Version 1.4. But for now you can set the following SEB Server setup setting within your application-prod.properties file or as ENV-Variable within your docker-compose setup:

`sebserver.webservice.api.admin.accessTokenValiditySeconds=-1`

Please note that if you set this via ENV-Variable you have to replace the "." with "_":

`sebserver_webservice_api_admin_accessTokenValiditySeconds=-1`

Then restart your services. This fixes the known bug so far.

For the next Version of SEB Server we fix this within the code as well as on the SEB side to let SEB handle expired SEB Server tokens more accurate.

**Comment by ano010** [comment]
Hi, @anhefti Thanks for the information. I have set the above-mentioned property as an environment variable. But seems like the issue is still there. Should I clear the database as well and restart the server?

**Comment by anhefti** [comment]
Hi. 
which issue exactly is still there? 

If you still have Missing SEB client connection from before (the change), just mark them as Disabled like described above.

It is possible that the old access token is still in place (until expiration) and will once again expire. But after that SEB Server generates a new access token. But you have to restart the SEB Server services after the settings change, at least the webservices (all of them). If you want you can clear the DB but to remove the old access token or if you have access, truncate the table oaut_access_token to force creating new tokens.

Please try again and if you still have SEB connections that are active in the beginning and then suddenly went to Missing, the issue still exists and the setting was probably not correctly set.
