### ISSUE TITLE
Search fields could use a hint (tooltip or similar)

### ISSUE THREAD

**Issue by lucaboesch** [SafeExamBrowser/seb-server#72]
As discussed in Winterthur, it would be nice if the search field could benefit from some tooltip or hint.

<img width="888" alt="image" src="https://user-images.githubusercontent.com/377279/205046998-5609716d-079d-4050-b547-97708d1a550c.png">

The table column are not entirely the same. For example, the date field looks for exams which are active at that day (open and not yet closed).

Thanks!

**Comment by anhefti** [comment]
done, comes with version 1.5
