### ISSUE TITLE
Moodle mod_quiz_get_quizzes_by_courses warning for course id 0 breaks fetching, probably

### ISSUE THREAD

**Issue by lucaboesch** [SafeExamBrowser/seb-server#74]
**Describe the bug**
This probably connects to #67.
Maybe, when fetching for courses on Moodle, SEB Server encounters a warning and then interrupts fetching, which results in an incomplete exam list. The precise problem might be bound to a Moodle misconfiguration itself, nonetheless, probably, skipping or circumventing the error could be managed.

**To Reproduce**
I have to drill down on what the exact cause is. Stack trace says (I think) that it tries to fetch quizzes of a course with ID 0. That is of course gibberish.
`
11:36:54.637 DEBUG [asyncService-1]:[ch.ethz.seb.sebserver.webservice.servicelayer.lms.impl.moodle.legacy.MoodleCourseAccess] There are warnings from Moodle response: Moodle: LmsSetup [id=3, institutionId=1, name=BFH Moodle, lmsType=MOODLE, lmsAuthName=<webservice username>, lmsAuthSecret=null, lmsApiUrl=<lms url>, lmsRestApiToken=null, proxyHost=null, proxyPort=null, proxyAuthUsername=null, proxyAuthSecret=null, active=true] request: mod_quiz_get_quizzes_by_courses warnings: 1 warning sample: Warning [item=course, itemid=0, warningcode=1, message=No access rights in course context]`

**Expected behavior**
Fetching of all exams works nonetheless.

**Setup (please complete the following information):**

- SEB Server Version 1.4.1-42c0732
- Docker on Ubuntu
- Firefox browser

**Comment by anhefti** [comment]
Hi Luca, thanks again for the information. 

SEB Server shows the warnings that it receives from Moodle responses in the logs. The whole log page would be interesting here to see what was requested for example and if there is an error from SEB Server afterwards.

It is possible that an unexpected error leads to a abortion of course fetching as I've this just checked in the code. Although if so you should also see the error: "Unexpected error while trying to get courses page...." just slightly after the warning log you described above. If there is no such error in the logs, it seems that SEB Server just prints the warnings received from Moodle response and go on with fetching. Why Moodle sends this warning is unclear to me. I've seen such warnings before even if the fetch was working as expected. But indeed the "0" quiz identifier might indicate a data inconsistency.

For your information, Amr is currently working hard on a Plugin to improve Moodle integration for SEB Server where also the course and quiz fetching shall be more efficient and less error prone. We expect to release this with next SEB Server version coming soon (April or Mai this Year).

Best,
Andreas

**Comment by anhefti** [comment]
Fixed for 1.5 and with new Moodle Plugin

**Comment by lucaboesch** [comment]
👍🏻👍🏻👍🏻 @anhefti 
I see there's a 1.5-dev branch and I noted that in a demo you gave recently in the bottom right corner it said 1.5 as version info.
Leads me to think you are in time for a a Q2/2023 release of version 1.5, aren't you?
Excellent.

Best,
Luca
