### ISSUE TITLE
Can not add new LMS setup

### ISSUE THREAD

**Issue by fishfree** [SafeExamBrowser/seb-server#81]
I got seb-server 1.5 stable running with https://github.com/SafeExamBrowser/seb-server-setup/blob/master/docker/prod/bundled/dockerhub/docker-compose.yml
However, I cannot add new items such as LMS setup as the screenshot below:
![image](https://github.com/SafeExamBrowser/seb-server/assets/1741341/574d2778-ad5f-4ea8-bf31-93a84bc4f584)

**Comment by anhefti** [comment]
Hi, It seems that your user doesn't have the right to do so. Maybe the user has only Exam Administrator role. The user needs Institutional Administrator rights to create a new LMS Setup. 
Do you also have different institutions? 
You you would like to describe your use-case and what you want to achieve, we can give you a guideline to do so.

**Comment by fishfree** [comment]
Thank you! The role & permission of SEB server is different from most of other systems.

**Comment by anhefti** [comment]
> Thank you! The role & permission of SEB server is different from most of other systems.

Yes, there are only four roles at the moment that has hard coded privileges, two for SEB Server administration and two for Exam setup and monitoring

- The **SEB Server Administrator** role is to maintain User Accounts and Institutions (multitenancy). This role can also view almost everything to be able to give advice.
- The **Institutional Administrator**  role has administrator rights for its own institution but cannot see other institutions, setup LMS bindings and so on.
- The **Exam Administrator** role is to setup an exam form LMS, import setup monitoring
- And the **Exam Supporter** role sees only exams that it as been applied to and can also monitor only them.

You can always combine the roles but there is no single item based privilege assignment possible yet but this would make it more complicated wouldn't it?
