### ISSUE TITLE
How to push SEB config to BYOD clients and Moodle LMS?

### ISSUE THREAD

**Issue by fishfree** [SafeExamBrowser/seb-server#85]
I mean, a step-by-step tutorial for how to seriously orgnize an examination is neccessary. Maybe:

1. Install SEB server quiz_access rule plugin in Moodle and setup REST access token;
2. Connect SEB server and Moodle;
3. Create a quiz in Moodle;
4. Import the quiz created in Moodle into SEB server
5. **Now the problem**: how to access the quiz respectively for Managed / BYOD devices? SEB client config is feasible for managed devices. But for BYOD devices, how to push the SEB config to clients?

**Comment by anhefti** [comment]
Hi, You can download the Connection Configuration from either either as a generic access-configuration within the Connection Configuration page. In this case a student is first presented with all running exams from the SEB Server on SEB startup and has to choose the right exam.

![image](https://github.com/SafeExamBrowser/seb-server/assets/39078777/cb931665-74b2-4c63-89ad-a2de69fe91e8)

Alternatively you can download the Connection Configuration within the Exam page for a preselected exam. Then the exam is already within the configuration and the student has not to select the exam.

![image](https://github.com/SafeExamBrowser/seb-server/assets/39078777/6395624a-ba09-44af-9e27-33863dcfcff6)


After you have downloaded the Connection Configuration you can deliver it to students how you want, within E-Mail or a download link on your exam portal server. A student with  BYOD must have installed the expected SEB version on its device and if the SEB is installed correctly files with "seb" extensions shall be loaded automatically within the SEB application

For more information on setup please also refer to the [SEB Server user documentation ](https://seb-server.readthedocs.io/en/latest/#)

**Comment by fishfree** [comment]
@anhefti Thank you for your help! However, I found nowhere the exam portal page you mentioned :-(

**Comment by anhefti** [comment]
A Exam portal page is not part of the SEB ecosystem. How you want to present the Connection Configuration to your students is completely up to you and there are many different ways how you as an exam provider deliver the configuration to your students. Via Mail, via self download links on a self hosted portal, deployed directly within a managed device that has SEB installed... and so on.
