### ISSUE TITLE
List of Configuration Template Attribute Values pagination after 5 entries is small

### ISSUE THREAD

**Issue by lucaboesch** [SafeExamBrowser/seb-server#88]
When looking at Configuration Template Attribute Values the list is limited to 5 entries.

A more vast list number and less pagination would be preferrable.

![SEBS_5_entries](https://github.com/SafeExamBrowser/seb-server/assets/377279/bbb6627b-fc9c-4b0b-8a62-14f2bb6a2ae1)

**Comment by anhefti** [comment]
Hi Luca, thanks for the input.
Currently this is the very same list a s displayed in the Exam Configuration / Application tab. Therefore the height if the list is restricted but there should be a scrollbar and the whole list should be scroll-able.

Anyway, I can try to adapt the list to the space available. This should be possible, or at least make the list in the Configuration Template section bigger then the one in the Exam Configuration.

Best

**Comment by anhefti** [comment]
Jira reference: SEBSERV-461
