### ISSUE TITLE
No automatic line wrap in the textareas for descriptions

### ISSUE THREAD

**Issue by michaelhq** [SafeExamBrowser/seb-server#93]
Word wrap is set to off in the textareas for the description in the forms for "Exam Template", "Exam Configuration" and "Configuration Templates".

1. Go to 'Exam Templates'
2. Click on 'Add Exam Template'
3. Paste or enter a text in the textarea for the description with more than 100 characters.
4. You will get no automatic line wrap of the text you entered (a manual line break with Shift + Enter works).

Expected behavior:
An automatic word wrap.

Screenshots
![grafik](https://github.com/SafeExamBrowser/seb-server/assets/11134268/20b5885d-e1d9-4a75-a8e3-a286e5526776)

The marked parameter in the html code is set to "off" instead to "on".
![grafik](https://github.com/SafeExamBrowser/seb-server/assets/11134268/284dbbea-381e-484f-8dfa-1b7ce68b0dab)

There is no word wrap too when viewing a configuration or template.
![grafik](https://github.com/SafeExamBrowser/seb-server/assets/11134268/7fe2e530-ea12-4db9-8ad4-9b1e0927db93)

After changing to "on".
![grafik](https://github.com/SafeExamBrowser/seb-server/assets/11134268/2ec184c8-1ccc-4afc-855d-d74dd830264b)

Setup
 - SEB Server Version 1.5.1
 - FHWN/BFH
 - Browsers all

**Comment by anhefti** [comment]
Hi,

Yes the Text Input field is just a ordinary text input with no auto-wrap. but you can add line-brakes when you enter the text for the description just with usual line-breaks:
![image](https://github.com/SafeExamBrowser/seb-server/assets/39078777/3c33d2b5-dca8-4358-8a54-2fb5e054f906)

![image](https://github.com/SafeExamBrowser/seb-server/assets/39078777/dbc956ea-deb3-4d00-9ea0-1df42650a7a3)

**Comment by michaelhq** [comment]
It is only a minor issue, but would it be possible just to change the described parameter in the code from "off" to "on" in a future release?

This would be a more common behavior with such input fields and perhaps more user-friendly.

**Comment by anhefti** [comment]
The problem here is that currently in SEB Server we use a Java Framework (Eclipse RAP) that generates all the HTML code with only a minor possibility to interfere with this HTML generation process of the Framework. 
I will have a look if I can change this setting and if so, we will adapt this for the next SEB Server version. 

In the long-term we plan to exchange the current GUI framework with a modern Type-Script (Vue) GUI.

**Comment by anhefti** [comment]
@michaelhq By the way, we just released the next patch for SEB Server v1.5.2. 
This fixes some major bugs within v1.5.1 (and v1.5.0): https://github.com/SafeExamBrowser/seb-server/releases/tag/v1.5.2
We recommend to update to v1.5.2 as soon as possible.

**Comment by michaelhq** [comment]
@anhefti: @lucaboesch installed the patch about 15 minutes after you published it this morning... 😃
