### ISSUE TITLE
Semicolon in short name of a course in Moodle leads to error message when importing an exam

### ISSUE THREAD

**Issue by michaelhq** [SafeExamBrowser/seb-server#96]
Hi,

The following issue appears in the context of using the Moodle SEB Server plugin ([https://github.com/ethz-let/moodle-quizaccess_sebserver](https://github.com/ethz-let/moodle-quizaccess_sebserver)), no test can be imported from a course if that course contains a semicolon in its short name.

1. Go to a course in moodle which has running quiz activities and insert in the course settings a semicolon in the short name: 
![grafik](https://github.com/SafeExamBrowser/seb-server/assets/11134268/2a411adc-a6ba-46fd-a9f9-d5f6a1292ac9)
2. Got on SEB server to "LMS Exam Lookup" and try to import the a quiz from these course, the following error window appears:
![grafik](https://github.com/SafeExamBrowser/seb-server/assets/11134268/0adf9800-9c48-4d5c-943e-bceff370bd3e)

Setup
 - SEB Server Version 1.5.3
 - Moodle SEB Server Plugin 0.2 (no error on Moodle side)

Workaround: Remove the semicolon in the short name ;-)

**Comment by anhefti** [comment]
Hi and thanks to pointing this out. We will try to reproduce and fix this this issues as soon as possible.
