### ISSUE TITLE
"URLFilterRules" table in a "Configuration Template" allows only five entries, entries are not written to "whitelistURLFilter" attribute

### ISSUE THREAD

**Issue by michaelhq** [SafeExamBrowser/seb-server#97]
Hi,

If you try to add a sixth entry in "URLFilterRules" attribute table in a "Configuration Template" the last entry is overwritten. In addition, entries are in not written as RegEx string to "whitelistURLFilter" attribute (which is important for the configuration of URL filters for SEB on Windows according to my tests).

1. Go to "Configuration Template"
2. Open an exiting template or create a new one
3. Enter six entries in the table of the URLFilterRules
4. Close attribute with "View Configuration Tempate", attribute is saved
5. reopen URLFilterRules, the fifth entry is missing, the sixth entry is the fifth one.
6. Changes in the URLFilterRules table are not written as RegeEx string to the "whitelistURLFilter" attribute (In the SEB config tool on Windows and the SEB preferences on macOS the whitelistURLFilter attribute is set correctly in the exported configuration file).

Expected behavior
All entries are saved in URLFilterRules tables and were written as RegEx string to whitelistURLFilter 

Setup:
 - SEB Server Version 1.5.3

Workaround:
Create configuration in Safe Exam Browser Windows or macOS, import it as "Exam Configuration", view imported "Exam Configuration" and "Save as Template".

**Comment by NadimETH** [comment]
Hi @michaelhq 

I was not able to reproduce the issue regarding the missing sixth entry in the table.

On first sight it looks like only 5 entries are visible:
![SEBSERV-480](https://github.com/SafeExamBrowser/seb-server/assets/138491408/1db59a61-5a58-4403-9f92-090e4b2c76b3)

Hovering over the table with your mouse reveals the scrollbar. Scroll down to see the other entries.

Please try again - if the bug still exists, provide your browser version and some screenshots.

The other issue regarding "whitelistURLFilter" is currently under review.

**Comment by anhefti** [comment]
We have clarified with the SEB developers that both SEB Settings, whitelistURLFilter and blacklistURLFilter are deprected (since SEB 3x) and not used anymore. Only the setting URLFilterRules is used.

Also whitelistURLFilter and blacklistURLFilter get soon removed in SEB Server.

**Comment by michaelhq** [comment]
Thank you for handling this issue.

I primarily use Mozilla Firefox on a daily basis for privacy reasons. I have now tested the whole thing with Google Chrome. This problem does not actually occur there. I have also tried the whole thing in Firefox's Safe Mode, it is the same behavior.

So it is a problem between the GUI of the SEB Server and Firefox. Can you please also test this with Firefox on one of your own systems?

Regarding whitelistURLFilter and blacklistURLFilter: Then these entries in the config tools on Windows and MacOS are only used for backward compatibility?

**Comment by anhefti** [comment]
Hi Michael

> Regarding whitelistURLFilter and blacklistURLFilter: Then these entries in the config tools on Windows and MacOS are only used for backward compatibility?

Yes, this is old legacy code from former SEB and SEB Configuration Tools and is deprected. SEB do not read this settings anymore but only the URLFilterRules setting.

> So it is a problem between the GUI of the SEB Server and Firefox. Can you please also test this with Firefox on one of your own systems?

I usually use Firefox (newest version) and I also don't get this issue there. Please be aware that the scroll bar only apears when you hover over the table input field:
![image](https://github.com/SafeExamBrowser/seb-server/assets/39078777/0bf11087-6554-4832-924b-d801489e9ccc)

We have another Issue (from Luca Bösch) to make this table bigger (more than 5 entires). Maybe this will allso be helpfull with this issue.

**Comment by michaelhq** [comment]
Hi Andreas

I am using the same version of Firefox.

After I deleted all entries in the table and saved it, it works with firefox too. The specific Configuration Template was imported from e seb-file contains URL-filter settings. Perhaps the issue lies in the import function.
